### ISSUE TITLE
File not found with singular glob myApp/app/meta/Pizza/invalid address or incorrect password.json

### ISSUE THREAD

**Issue by zcmack** [blockapps/pizza-demo#8] opened 2016-07-07 20:56 UTC
bloc appears to crash when following the [pizza-demo instructions.](https://github.com/blockapps/pizza-demo/blob/develop/docs/how-it-works.md) If I attempt to submit a new pizza contract (selecting one topping with an integer value) it exits with the following error: 

+++++++++++++++++++++++++++++++++++++

POST /users/pizzaMaker/null/contract 200 37.499 ms - 37

OPTIONS /users/pizzaMaker/null/contract/Pizza/invalid%20address%20or%20incorrect%20password/call 204 2.984 ms - -

args: {"price":"6","topping":"pepperoni"}

method: setUpPizzaDetails

POST /users/pizzaMaker/null/contract/Pizza/invalid%20address%20or%20incorrect%20password/call 200 6.781 ms - 18

error: Error: File not found with singular glob: pizza-demo/myApp/app/meta/Pizza/invalid address or incorrect password.json

**Comment by jcrain** [comment] 2016-07-07 22:44
@zcmack  `/users/pizzaMaker/null/` looks there was an issue with pizza maker key. Try removing the `app/users/` directory and recreating the keys.

**Comment by kenken64** [comment] 2017-02-03 21:44
When you generate the key for the respective actor key in the password "thepass"

**Comment by kenken64** [comment] 2017-02-03 21:45
after i have pass thru this fix i end up with some other stuff ....
my bloc app just crashes!

**Comment by kejace** [comment] 2017-05-02 16:22
Closing this. Feel free to re-open with instructions how to reproduce if the issue is still there.

**Closed by kejace** 2017-05-02 16:22 UTC
